
# wicd-on
- name: make dir
  file:
    state: directory
    path: "{{item}}"
  loop: ["{{ansible_facts.user_dir}}/scripts/wicd-on"]
- name: copy wicd-on scripts
  template:
    src: "templates/home/user/scripts/wicd-on/{{item}}.j2"
    dest: "{{ansible_facts.user_dir}}/scripts/wicd-on/{{item}}"
    mode: '0755'
  loop: ["wicd-on.py", "wicd-on.sh"]
- name: add link to ~/bin
  file:
    state: link
    path: "{{ansible_facts.user_dir}}/bin/wicd-on"
    src: "{{ansible_facts.user_dir}}/scripts/wicd-on/wicd-on.sh"
- name: check for wicd networks in bash profile
  shell: "grep WICD_ON_NETWORKS {{ ansible_facts.user_dir }}/.bash_profile"
  register: grep_wicd_on_networks
  failed_when: grep_wicd_on_networks.rc == 2
  changed_when: grep_wicd_on_networks.rc != 0
- name: create environment variable for known networks
  lineinfile:
    path: "{{ansible_facts.user_dir}}/.bash_profile"
    line: 'export WICD_ON_NETWORKS="";'
  when: grep_wicd_on_networks.rc != 0