---
- hosts: all
  vars:
    i3lock_background_image: "{{ansible_facts.user_dir}}/Pictures/sunrise.png"
  roles:
    - bash-prompt
    - i3blocks-bar
    - i3-volume
    - i3-dpms
    - i3-screencap
    - wicd-on
    - role: bash-aliases
      vars:
        bash_aliases:
          - alias poweroff='sudo poweroff';
          - alias reboot='sudo reboot';
          - alias python='python3';
          - alias pip='pip3';
  connection: local
  tasks:


  # blah blah
  - name: blah
    debug:
      msg: "blah"
