---
- hosts: all
  roles:
    - bash-prompt
  connection: local
  vars:
    raise_volume_keysym: XF86AudioRaiseVolume
    lower_volume_keysym: XF86AudioLowerVolume
    mute_volume_keysym: XF86AudioMute

    lock_screen_keysym: XF86ScreenSaver
    i3lock_background_image: "{{ansible_facts.user_dir}}/Pictures/sunrise.png"
  tasks:

  # i3blocks
  #- name: mkdir -p ~/.config/i3blocks/scripts
  #  shell: mkdir -p ~/.config/i3blocks/scripts
  - name: make dir
    file:
      state: directory
      path: "{{ansible_facts.user_dir}}/.config/i3blocks/scripts"
  - name: apt install i3blocks
    apt:
      name: i3blocks
    become: yes
  - name: copy i3blocks python files
    template:
      src: "template/home/user/.config/i3blocks/scripts/{{item}}.j2"
      dest: "{{ansible_facts.user_dir}}/.config/i3blocks/scripts/{{item}}"
      mode: '0755'
    loop: ["battery.py", "disk.py", "loadavg.py", "memory.py", "network.py"]
  - name: copy i3blocks config
    template:
      src: "template/home/user/.config/i3blocks/config.j2"
      dest: "{{ansible_facts.user_dir}}/.config/i3blocks/config"
  - name: configure i3 to use i3blocks
    blockinfile:
      path: "{{ansible_facts.user_dir}}/.config/i3/config"
      backup: yes
      block: |
        bar {
          status_command i3blocks
          tray_output primary
          colors {
            background #0e0e0e
          }
        }
  
  # i3 keyboard bindsyms: volume
  - name: add volume control bindsyms to i3 config
    lineinfile:
      path: "{{ansible_facts.user_dir}}/.config/i3/config"
      line: "{{item}}"
    loop:
      - "bindsym {{raise_volume_keysym}} exec amixer -q set Master 10%+ unmute && pkill -SIGRTMIN+10 i3blocks"
      - "bindsym {{lower_volume_keysym}} exec amixer -q set Master 10%- && pkill -SIGRTMIN+10 i3blocks"
      - "bindsym {{mute_volume_keysym}} exec amixer -q set Master toggle && pkill -SIGRTMIN+10 i3blocks"
  
  # i3: locking/power
  - name: make dir
    file:
      state: directory
      path: "{{ansible_facts.user_dir}}/scripts"
  - name: apt install i3lock
    apt:
      name: i3lock
    become: yes
  - name: copy lock script to ~/scripts/
    template:
      src: "template/home/user/scripts/{{item}}.j2"
      dest: "{{ansible_facts.user_dir}}/scripts/{{item}}"
      mode: '0755'
    loop: ["lock.sh", "autolock.sh"]
  - name: add screen locking / sleep bindsyms to i3
    lineinfile:
      path: "{{ansible_facts.user_dir}}/.config/i3/config"
      line: "{{item}}"
    loop:
      - "bindsym {{lock_screen_keysym}} exec {{ansible_facts.user_dir}}/scripts/lock.sh"
      - "exec --no-startup-id {{ansible_facts.user_dir}}/scripts/autolock.sh"
  
  # i3 keyboard bindsyms: screen capture
  - name: make dir
    file:
      state: directory
      path: "{{ansible_facts.user_dir}}/scripts/screenshot"
  - name: apt install scrot
    apt:
      name: scrot
    become: yes
  - name: copy screenshot script to ~/scripts/
    template:
      src: "template/home/user/scripts/screenshot/{{item}}.j2"
      dest: "{{ansible_facts.user_dir}}/scripts/screenshot/{{item}}"
      mode: '0755'
    loop: ["screenshot.py"]
  - name: add screen capture bindsyms to i3 config
    lineinfile:
      path: "{{ansible_facts.user_dir}}/.config/i3/config"
      line: "{{item}}"
    loop:
      - "bindsym Print exec --no-startup-id {{ansible_facts.user_dir}}/scripts/screenshot/screenshot.py screen"
      - "bindsym Shift+Print exec --no-startup-id {{ansible_facts.user_dir}}/scripts/screenshot/screenshot.py selection"
  
  # wicd-on
  - name: make dir
    file:
      state: directory
      path: "{{item}}"
    loop:
      - "{{ansible_facts.user_dir}}/bin"
      - "{{ansible_facts.user_dir}}/scripts/wicd-on"
  - name: copy wicd-on scripts
    template:
      src: "template/home/user/scripts/wicd-on/{{item}}.j2"
      dest: "{{ansible_facts.user_dir}}/scripts/wicd-on/{{item}}"
      mode: '0755'
    loop: ["wicd-on.py", "wicd-on.sh"]
  - name: add link to ~/bin
    file:
      state: link
      path: "{{ansible_facts.user_dir}}/bin/wicd-on"
      src: "{{ansible_facts.user_dir}}/scripts/wicd-on/wicd-on.sh"

  # blah blah
  - name: blah
    debug:
      msg: "blah"
