---
- hosts: all
  vars:
    i3lock_background_image: "{{ansible_facts.user_dir}}/Pictures/sunrise.png"
  roles:
    - bash-prompt
    - i3blocks-bar
    - i3-volume
    - i3-dpms
    - i3-screencap
    - wicd-on
  connection: local
  tasks:


  # blah blah
  - name: blah
    debug:
      msg: "blah"
