---
- hosts: all
  vars:
    i3lock_background_image: "{{ansible_facts.user_dir}}/Pictures/sunrise.png"
  roles:
    - bash-prompt
    - i3blocks-bar
    - i3-volume
    - i3-dpms
    - i3-screencap
  connection: local
  tasks:
  
  # wicd-on
  - name: make dir
    file:
      state: directory
      path: "{{item}}"
    loop:
      - "{{ansible_facts.user_dir}}/bin"
      - "{{ansible_facts.user_dir}}/scripts/wicd-on"
  - name: copy wicd-on scripts
    template:
      src: "template/home/user/scripts/wicd-on/{{item}}.j2"
      dest: "{{ansible_facts.user_dir}}/scripts/wicd-on/{{item}}"
      mode: '0755'
    loop: ["wicd-on.py", "wicd-on.sh"]
  - name: add link to ~/bin
    file:
      state: link
      path: "{{ansible_facts.user_dir}}/bin/wicd-on"
      src: "{{ansible_facts.user_dir}}/scripts/wicd-on/wicd-on.sh"

  # blah blah
  - name: blah
    debug:
      msg: "blah"
