---
# tasks file for bash-aliases
- debug:
    var: bash_aliases_file
- name: get info on bash aliases file
  stat:
    path: "{{bash_aliases_file}}"
  register: bash_aliases_file_stat
- name: create bash aliases file
  file:
    state: touch
    path: "{{bash_aliases_file}}"
  when: bash_aliases_file_stat.stat.exists == False
- name: bash aliases file populated
  lineinfile:
    path: "{{bash_aliases_file}}"
    line: "{{item}}"
  loop: "{{bash_aliases}}"
- name: source from ~/.bashrc
  blockinfile:
    path: "{{ansible_facts.user_dir}}/.bashrc"
    block: |
      # Alias definitions.
      # You may want to put all your additions into a separate file like
      # ~/.bash_aliases, instead of adding them here directly.
      # See /usr/share/doc/bash-doc/examples in the bash-doc package.

      if [ -f {{bash_aliases_file}} ]; then
          . {{bash_aliases_file}}
      fi