# i3: locking/power

- import_tasks: debian.yml
  when: ansible_facts['os_family']|lower == 'debian'

- name: make dir
  file:
    state: directory
    path: "{{ansible_facts.user_dir}}/scripts/i3-dpms"
- name: copy lock script to ~/scripts/i3-dpms
  template:
    src: "templates/home/user/scripts/i3-dpms/{{item}}.j2"
    dest: "{{ansible_facts.user_dir}}/scripts/i3-dpms/{{item}}"
    mode: '0755'
  loop: ["lock.sh", "autolock.sh"]
- name: add screen locking / sleep bindsyms to i3
  lineinfile:
    path: "{{ansible_facts.user_dir}}/.config/i3/config"
    line: "{{item}}"
  loop:
    - "bindsym {{lock_screen_keysym}} exec {{ansible_facts.user_dir}}/scripts/i3-dpms/lock.sh"
    - "exec --no-startup-id {{ansible_facts.user_dir}}/scripts/i3-dpms/autolock.sh"